my_app/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
    path('add/', views.add_thumbnails, name='add'),
    path('register/', views.register, name='register'),
    path('login_status/', views.login_status, name='login_status'),
    path('404/', views.not_found, name='not_found'),
    path('my_thumbnails/', views.my_thumbnails, name='my_thumbnails'),
    path('edit/<int:pool_id>/', views.edit_thumb, name='edit,'),
    path('delete-confirm/<int:pool_id>/', views.delete, name='delete'),
    path('detail/<int:pool_id>/', views.detail, name='detail'),
]   

poll/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('my_app.urls')),
    path('', include('django.contrib.auth.urls')),
]

templates/base.html
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My Thumbnails Vote {% block title %}{% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap/css/bootstrap.min.css' %}">
    {% block style %}
    {% endblock %}

</head>

<body>
    {% if request.user.is_authenticated %}
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand ml-5" href="{% url 'home:index' %}">Thumbnails Vote</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse mr-5" id="navbarSupportedContent">
            <ul class="navbar-nav ml-lg-auto text-center">
                <li class="nav-item active">
                    <a class="nav-link text-capitalize" href="{% url 'home:my_thumbnails' %}">My thumbnails</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link text-capitalize" href="{% url 'home:add' %}">Add Thumbnails</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link text-capitalize text-danger" href="../../../logout/">logout</a>
                </li>
            </ul>
        </div>
    </nav>

    {% else %}
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand ml-5" href="{% url 'home:index' %}">Thumbnails Vote</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse mr-5" id="navbarSupportedContent">
            <ul class="navbar-nav ml-lg-auto text-center">
                <li class="nav-item active">
                    <a class="nav-link text-capitalize" href="login/">Login</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link text-capitalize" href="{% url 'home:register' %}">register</a>
                </li>
            </ul>
        </div>
    </nav>
    {% endif %}
    {% block content %}
    {% endblock content %}
    <!-- bootstrap js -->
    <script type="text/javascript" src="{% static 'css/bootstrap/js/bootstrap.min.js' %}"></script>
    <!-- another js -->
    <script type="text/javascript" src="{% static 'js/jquery-3.5.1.slim.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
</body>

</html>

templates/logged_in.html
{% extends 'base.html' %}

{% block title %}
| You Are Already Logged in
{% endblock title %}

{% load static %}

{% block content %}
<div class="container py-5">
    <div class="row">
        <div class="col-5 mx-auto">
            <div class="card">
                <div class="card-header bg-primary">
                    <h1 class="text-center">Login Status</h1>
                </div>
                <div class="card-body">
                    <h4 class="text-center text-capitalize">you are already logged in, in this site</h4>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript" src="{% static 'css/bootstrap/js/bootstrap.min.js' %}"></script>
<!-- another js -->
<script type="text/javascript" src="{% static 'js/jquery-3.5.1.slim.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>

{% endblock content %}